### PR TITLE
Encode query parameter

### LINKED ISSUE #4185: Single hit catalog request using non-encoded "=" operator.
Example: Trying to import „Volkstänze aus dem Harz“ from Hebis catalog. Wrong request URL is built:

    http://sru.hebis.de/sru/DB=2.1?version=1.1&operation=searchRetrieve&recordSchema=pica&
        recordPacking=xml&maximumRecords=1&query=pica.ppn=406442703
                                                         ^

The catalog returns the wrong record ([try](http://sru.hebis.de/sru/DB=2.1?version=1.1&operation=searchRetrieve&recordSchema=pica&recordPacking=xml&maximumRecords=1&query=pica.ppn=406442703)).

**Goal:** The `=` sign in the `query=` parameter must be encoded (`%3D`). Correct ([try](http://sru.hebis.de/sru/DB=2.1?version=1.1&operation=searchRetrieve&recordSchema=pica&recordPacking=xml&maximumRecords=1&query=pica.ppn%3D406442703)):

    http://sru.hebis.de/sru/DB=2.1?version=1.1&operation=searchRetrieve&recordSchema=pica&
        recordPacking=xml&maximumRecords=1&query=pica.ppn%3D406442703
                                                         ^^^

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #4185

### CODE REVIEW

File: Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java [hunk 1]
```diff
@@ -300,6 +298,32 @@ private DataRecord performQueryToRecord(String queryURL, String identifier) thro
...
+     * The exception announced by {@code URLEncoder} cannot occur if a Charset
+     * object is used.
+     *
+     * TODO: This method can be replaced by URLEncoder.encode(String, Charset)
+     * in Java ≥ 10.
+     */
+    private static String encodeQueryParameter(String value, Charset charset) {
+        try {
+            return URLEncoder.encode(value, charset.toString());
+        } catch (UnsupportedEncodingException e) {
```
Comment (Kathrin-Huber) [inline Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java:322]: why are you changing the Exception here?

Comment (matthias-ronge) [reply Kitodo-Query-URL-Import/src/main/java/org/kitodo/queryurlimport/QueryURLImport.java:322]: Because `UnsupportedEncodingException` is a checked exception which you would have to declare everywhere, but it cannot be thrown since the method takes a `Charset`, not an arbitrary string.
Declaring an exception that is never thrown is bad design.
