### PR TITLE
Don't complain required fields from an altogether empty metadata group

### LINKED ISSUE #5297: Validation mis-enforces required fields in empty always-showing metadata group
**Describe the bug**
If you have an `alwaysShowing` nested metadata key, with sub-keys that are declared `minOccurs` > 0, in process creation, the validation complains about these fields to be empty and refuses creating the process.

**Expected behavior**
If the `alwaysShowing` metadata group is all empty, the validation should not complain about these fields to be filled. If there is any data in any sub-field of the metadata group, then the validation should require these fields to be filled.

### PR DESCRIPTION
**Pull request by matthias-ronge**
If for a metadata group, all children are empty, then the whole group is empty, and then, ignore 'minOccurs' from the child.

Fixes #5297

### CODE REVIEW

File: Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java [hunk 1]
```diff
@@ -86,6 +87,12 @@ public boolean isUndefined() {
     }
 
     public boolean isRequired() {
+        if (container != null && container.getChildMetadata().isEmpty()) {
```
Comment (IkramMaalej) [inline Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java:90]: The required simple metadata of a 'docType' are also no longer required.
The simple metadata also has a container wich is the selected docType (volume...) , so this condition "Container != null && container.getChildMetadata().isEmpty()" is not precise enough to distinguish between simple metadata of  the selected docType or simple metadata of a metadata group.

**Review by IkramMaalej — CHANGES_REQUESTED** [review]

File: Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java (hunk 1 above)
Comment (matthias-ronge) [reply Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java:90]: Since a docType is “simple”, it shouldn't have a container, or am I misunderstanding something?

Can you give me an example (a ruleset) where the problem occurs?

Comment (IkramMaalej) [reply Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessSimpleMetadata.java:90]: The doctype itself doesn't have a container, but the simple metadata like "HaupTitel" has a container, which is the doctype (e.g. volume)  and where all the metadata of the doctype are located.

**Review by IkramMaalej — APPROVED** [review]
