### PR TITLE
fix workflow creation on migration

### LINKED ISSUE #3754: Prepared workflow is created incomplete
The workflow was created from the virtual machine that was prepared for the migration workshop. There are missing some transitions here. The missing transitions were drawn in by hand:

Anmerkung 2020-06-10 133723b

### LINKED ISSUE #3755: First task of prepared workflow has no state set
The workflow was created from the virtual machine that was prepared for the migration workshop. The first task is no editing status set:

Screenshot

### LINKED ISSUE #3757: Workflow name is not updated in the dialog
When creating workflow in migration, when leaving the editor, the workflow has been renamed, but the name ChangeMe  is displayed in the dialog.

Screenshot

### LINKED ISSUE #3758: Workflow cannot be saved
When trying to saving a workflow, it gets the following error. This was happening with the workflow from the migration test VM which did not get all the arrows (after correcting them manually):

Date/time: 2020-06-10 13:47:03  
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0  
User IP: 192.168.91.1  
Request URI: /kitodo/pages/workflowEdit.jsf  
Ajax request: Yes  
Status code: 500  
Exception type: class org.camunda.bpm.model.xml.ModelParseException  
Exception message: SAXException while parsing input stream  
Exception UUID:  
Stack trace:

```
    org.camunda.bpm.model.xml.ModelParseException: SAXException while parsing input stream
    	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:245)
    	at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.parseModelFromStream(AbstractModelParser.java:98)
    	at org.camunda.bpm.model.bpmn.impl.BpmnParser.parseModelFromStream(BpmnParser.java:65)
    	at org.camunda.bpm.model.bpmn.Bpmn.doReadModelFromInputStream(Bpmn.java:249)
    	at org.camunda.bpm.model.bpmn.Bpmn.readModelFromStream(Bpmn.java:131)
    	at org.kitodo.production.workflow.model.Reader.loadProcess(Reader.java:118)
    	at org.kitodo.production.workflow.model.Reader.<init>(Reader.java:67)
    	at org.kitodo.production.workflow.model.Converter.<init>(Converter.java:63)
    	at org.kitodo.production.forms.WorkflowForm.hasMultipleSructureTreeConfiguration(WorkflowForm.java:175)
    	at org.kitodo.production.forms.WorkflowForm.saveAndRedirect(WorkflowForm.java:146)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
    	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
    	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
    	at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
    	at org.springframework.faces.webflow.FlowActionListener.processAction(FlowActionListener.java:71)
    	at org.springframework.faces.model.SelectionTrackingActionListener.processAction(SelectionTrackingActionListener.java:64)
    	at javax.faces.component.UICommand.broadcast(UICommand.java:120)
    	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
    	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
    	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
    	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
    	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
    	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:69)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
    	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:56)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
    	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: org.xml.sax.SAXException: Error: URI=null Line=42: cvc-complex-type.4: Attribut 'sourceRef' muss in Element 'bpmn2:sequenceFlow' vorkommen.
    	at org.camunda.bpm.model.xml.impl.util.DomUtil$DomErrorHandler.error(DomUtil.java:202)
    	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:137)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
    	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.addDefaultAttributes(XMLSchemaValidator.java:2937)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2055)
    	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:761)
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
    	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
    	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
    	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
    	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
    	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
    	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    	at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:240)
    	... 90 more
```

Database to reproduce this: [dump.sql](https://gist.github.com/matthias-ronge/0149beb6410bf8bc23cab42164d970b1)

Steps to reproduce: Go to system » migrate. Click “Create workflow”, select all projects, proceed, select first line from database (with 5 processes). In the window that appears, choose “create new workflow”. Do required changes to workflow (add missing arrows, assign roles to steps), click “save”.

### LINKED ISSUE #3759: Migration creates workflow despite canceling
If you create a new workflow in the migration but then click on Cancel, the workflow is still created in the background. You cannot create any other workflows no more, because the error then arises: File cannot be saved. You have to go to _Project » Workflows_ and delete ChangeMe manually.

### LINKED ISSUE #3760: Hibernate error when creating template from workflow by migration
In migration, a workflow was created, now you want to create production template. You click on "Create new production template". The error is produced:

Date/time: 2020-06-10 14:01:38  
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0  
User IP: 192.168.91.1  
Request URI: /kitodo/pages/system.jsf  
Ajax request: Yes  
Status code: 500  
Exception type: class java.lang.IllegalStateException  
Exception message: Multiple representations of the same entity [org.kitodo.data.database.beans.Process#4] are being merged. Detached: [PharZefD_129464317_26_Ha-121-26 [4]]; Detached: [PharZefD_129464317_26_Ha-121-26 [4]]  
Exception UUID:  
Stack trace:

```
    java.lang.IllegalStateException: Multiple representations of the same entity [org.kitodo.data.database.beans.Process#4] are being merged. Detached: [PharZefD_129464317_26_Ha-121-26 [4]]; Detached: [PharZefD_129464317_26_Ha-121-26 [4]]
    	at org.hibernate.event.internal.EntityCopyNotAllowedObserver.entityCopyDetected(EntityCopyNotAllowedObserver.java:45)
    	at org.hibernate.event.internal.MergeContext.put(MergeContext.java:245)
    	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:322)
    	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:172)
    	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:113)
    	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:803)
    	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:776)
    	at org.hibernate.engine.spi.CascadingActions$6.cascade(CascadingActions.java:261)
    	at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:492)
    	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:416)
    	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
    	at org.hibernate.engine.internal.Cascade.cascadeCollectionElements(Cascade.java:525)
    	at org.hibernate.engine.internal.Cascade.cascadeCollection(Cascade.java:456)
    	at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:419)
    	at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218)
    	at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151)
    	at org.hibernate.event.internal.DefaultMergeEventListener.cascadeOnMerge(DefaultMergeEventListener.java:519)
    	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:346)
    	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:172)
    	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:70)
    	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
    	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:783)
    	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:770)
    	at org.kitodo.data.database.persistence.BaseDAO.storeObject(BaseDAO.java:349)
    	at org.kitodo.data.database.persistence.BaseDAO.save(BaseDAO.java:86)
    	at org.kitodo.production.services.data.base.SearchDatabaseService.saveToDatabase(SearchDatabaseService.java:64)
    	at org.kitodo.production.services.data.base.SearchService.save(SearchService.java:268)
    	at org.kitodo.production.services.migration.MigrationService.addProcessesToTemplate(MigrationService.java:198)
    	at org.kitodo.production.forms.MigrationForm.useExistingTemplate(MigrationForm.java:388)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
    	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
    	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
    	at org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:74)
    	at org.springframework.faces.webflow.FlowActionListener.processAction(FlowActionListener.java:71)
    	at org.springframework.faces.model.SelectionTrackingActionListener.processAction(SelectionTrackingActionListener.java:64)
    	at javax.faces.component.UICommand.broadcast(UICommand.java:120)
    	at javax.faces.component.UIData.broadcast(UIData.java:1732)
    	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
    	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
    	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
    	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
    	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
    	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
    	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:69)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
    	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:86)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
    	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:155)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
    	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
    	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
    	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
    	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
    	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Thread.java:748)
```

### LINKED ISSUE #3761: Production template is created from wrong workflow file ChangeMe.bpnm20.xml
In migration, you have created a workflow. You assigned a role to each step and save successfully. No error message shows. Then you assign processes to production template. This seems to work, but in the log file, the error message is recorded:

```
[ERROR] 2020-06-10 14:17:32.633 [http-nio-8080-exec-1] MigrationForm - errorSaving
org.kitodo.exceptions.WorkflowException: Der Workflowaufgabe 'Begutachtung Bestandserhaltung' wurden keine Rollen zugewiesen.
	at org.kitodo.production.workflow.model.Converter.getTask(Converter.java:139) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.workflow.model.Converter.validateWorkflowTaskList(Converter.java:93) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.workflow.model.Converter.convertWorkflowToTemplate(Converter.java:70) ~[classes/:3.2.0-SNAPSHOT]
	at org.kitodo.production.forms.MigrationForm.createNewTemplate(MigrationForm.java:406) [classes/:3.2.0-SNAPSHOT]
	...
```

It appears that the state in which the Workflow Editor started is used to create the production template. When saving, the status is either not saved or it is not updated internally.

Database to reproduce this: [dump.sql](https://gist.github.com/matthias-ronge/0149beb6410bf8bc23cab42164d970b1)

Steps to reproduce: Go to system » migrate. Click “Create workflow”, select all projects, proceed, select second line from database (with 4 processes). In the window that appears, choose “create new workflow”. Do required changes to workflow (assign roles), click “save”. Create production template.

The production template has no steps. If you try to run hierarchy migration, creation of superior processes fails in validation step.

### PR DESCRIPTION
**Pull request by Kathrin-Huber**
fixes #3759
resolves #3760
fix #3761
closes #3754
fixed #3758
close #3757
resolved #3755

### CODE REVIEW

**Comment by solth** [comment]
Bildschirmfoto 2020-07-07 um 11 42 07

:dizzy_face: :boom:

**Comment by Kathrin-Huber** [comment]
schneiderlein_groß-1100x530-1506408129

File: Kitodo/src/main/java/org/kitodo/production/migration/XmlGenerator.java [hunk 1]
```diff
@@ -50,21 +51,22 @@ static String generateTask(Task task) {
      *            for sequence flow
      * @return generated task
      */
-    static String generateTask(Task task, String sourceReference, String targetReference) {
+    static String generateTask(Task task, String sourceReference, String targetReference, int ordering) {
```
Comment (solth) [inline Kitodo/src/main/java/org/kitodo/production/migration/XmlGenerator.java:54]: You could probably remove the third parameter `targetReference` - because it is always `"Task_" + order` - so simplify the method signature a little bit to
`static String generateTask(Task task, String sourceReference, int ordering)`
