### PR TITLE
Sort processes for desktop window right after index query

### LINKED ISSUE #3296: Desktop should select the correct process
From the desktop page, when you open a process in the metadata editor, the wrong process opens.

**Goal:** The selected process should be opened. (The same should apply to deletion; needs review)

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #3296

### CODE REVIEW

File: Kitodo/src/main/java/org/kitodo/production/forms/DesktopForm.java [hunk 1]
```diff
@@ -99,6 +100,7 @@ public DesktopForm() {
         try {
             if (ServiceManager.getSecurityAccessService().hasAuthorityToViewProcessList() && processList.isEmpty()) {
                 processList = ServiceManager.getProcessService().loadData(0, 10, SORT_ID, SortOrder.DESCENDING, null);
+                Collections.sort(processList, (one, other) -> other.getId() - one.getId());
```
Comment (solth) [inline Kitodo/src/main/java/org/kitodo/production/forms/DesktopForm.java:103]: Why is this neccessary? The processes are already returned in a sorted list, as indicated by the `SORT_ID` constant passed as the third parameter to `loadData` in the previous line, aren't they?

If you just want to reverse the order and start with the lowest ID, you should use `SortOrder.ASCENDING` instead of `DESCENDING`, I guess.

File: Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/processesWidget.xhtml [hunk 2]
```diff
@@ -20,7 +20,6 @@
                  value="#{DesktopForm.processes}"
                  scrollable="true"
                  styleClass="default-layout"
-                 sortBy="#{process.id}"
```
Comment (solth) [inline Kitodo/src/main/webapp/WEB-INF/templates/includes/desktop/processesWidget.xhtml:23]: If you remove `sortBy`, you should probably also remove the following line, because `sortOrder` doesn't make sense without `sortBy`.
