### PR TITLE
use keyword for wildcardsearch

### LINKED ISSUE #3938: Wildcard search does not work properly
### Problem
The wildcard search is only possible in specific parts of the process title:

1. **"7746**" has the following results: 
- Aben_**7746**18868-1873032402_02-a
- Aben_**7746**18868-1873
- ...

2. "**1873**" has the following results: 
- Aben_774618868-**1873**032402_02-a
- Aben_774618868-**1873**
- ...

3. "Aben_774618868-1873" has no results
- It seems as if "-" blocks the wildcard search. 

### Solution
It should be possible to search for "Aben_774618868-1873032" and get the following results: 
- Aben_774618868-18730321
- Aben_774618868-18730322

### PR DESCRIPTION
**Pull request by Kathrin-Huber**
fixes #3938

### CODE REVIEW

File: Kitodo/src/test/java/org/kitodo/production/services/data/ProcessServiceIT.java [hunk 1]
```diff
@@ -217,6 +218,22 @@ public void shouldFindByMetadataContent() throws DataException {
         assertEquals(processNotFound, 1, processService.findByAnything("SecondMetaShort").size());
     }
 
+    @Test
+    public void shouldFindProcessWithUnderscore() throws DataException, DAOException {
+        Project projectDTO = ServiceManager.getProjectService().getById(1);
```
Comment (solth) [inline Kitodo/src/test/java/org/kitodo/production/services/data/ProcessServiceIT.java:223]: Why is this variable called `projectDTO`? It is an instance of `Project`, not `ProjectDTO`.

**Review by solth — APPROVED** [review]
