### PR TITLE
Fix several folder issues

### LINKED ISSUE #3187: 3.0: Duplication of project folders
A project folder may get duplicated in the project edit page:

Screenshot_2020-02-13 Kitodo Production

Create a new project, go to the folders section and create a folder and confirm. Open the folder dialog and confirm again. Now the folder gets displayed twice. 
After that,
- the mouse cursor stays in wait mode.
-  if you emmediately click on "Save", Kitodo doesn't redirect (the project, however is created but I don't know if only partially?).
- it won't show the folder edit dialog and you won't be able to delete the folder.

An exception is logged:

```
 java.lang.IllegalStateException: Duplicate key images, DEFAULT
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        ...
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.kitodo.production.forms.ProjectForm.getFolderMap(ProjectForm.java:490)
        at org.kitodo.production.forms.ProjectForm.setPreview(ProjectForm.java:592)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

If you reload the page (F5, not Ctrl-F5) , you can go on configuring the project. Esp. you can delete the duplicate folder entry and save the project.

### LINKED ISSUE #3340: The set source for folder use (projects) disappears
If you have selected a file group as image generation source, and then change either the folder or the METS filegroup of it, the selection of the drop-down is reset.

### LINKED ISSUE #3731: Edit folder again crashes when creating project
If you create a new project, add folders, says OK, then want to change folders again: The page crashes.

```
java.lang.IllegalStateException: Duplicate key MAX, MAX (attempted merging values MAX, MAX and MAX, MAX)
    at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
    at java.base/java.util.stream.Collectors.lambda$uniqKeysMapMerger$0(Collectors.java:155)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.combine(ReduceOps.java:174)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.combine(ReduceOps.java:160)
    at java.base/java.util.stream.ReduceOps$ReduceTask.onCompletion(ReduceOps.java:959)
    at java.base/java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:592)
    at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:328)
    at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
    at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at org.kitodo.production.forms.ProjectForm.getFolderMap(ProjectForm.java:490)
    at org.kitodo.production.forms.ProjectForm.setPreview(ProjectForm.java:592)
```

**Goal:** It should be possible to edit folders.

### LINKED ISSUE #3775: Creating a project with Folder of type "PDF" crashes with Exception
Version 3.2 - build 09.06.2020:

I have tried to create in the project a folder like this:
grafik
This has crashed with an expection like this:
grafik

--> please check

### PR DESCRIPTION
**Pull request by matthias-ronge**
Fixes #3187, fixes #3340, fixes #3731, fixes #3775

### CODE REVIEW

File: Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Folder.java [hunk 1]
```diff
@@ -388,13 +391,21 @@ public void setDpi(Integer dpi) {
...
+     * the folder and may therefore only be set if the object is not yet
+     * persisted ({@code id} is null) or the object is being created
+     * ({@code fileGroup} is null).
      *
      * @param fileGroup
      *            file group to set
      */
     public void setFileGroup(String fileGroup) {
-        this.fileGroup = fileGroup;
+        if (fileGroup.equals(this.fileGroup) || Objects.isNull(this.fileGroup) || Objects.isNull(id)) {
```
Comment (Kathrin-Huber) [inline Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Folder.java:403]: You are throwing an Exception to the frontend, this will lead to the error page. Please handle the "else" different. Maybe just don't set the fileGroup for now.

Comment (matthias-ronge) [reply Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Folder.java:403]: I don't like this suggestion. This is an unchecked exception. [Unchecked exceptions should be thrown if there is a programming error.](https://stackoverflow.com/a/19061110) At the moment this exception is never thrown because our program behaves correctly. It would be thrown if someone programmed something new and used the object incorrectly. That was the reason why I programmed it that way. Simply not setting the filegroup would lead to data loss and, as a consequence, to behavior that is difficult to understand. I find that awkward. If you do not agree with this, it would be better not to check here at all. If someone changes the value and doesn't know what he's doing, it's his own fault then.

Comment (Kathrin-Huber) [reply Kitodo-DataManagement/src/main/java/org/kitodo/data/database/beans/Folder.java:403]: so don't check at all
