### PR TITLE
Correction comment state

### LINKED ISSUE #5676: Marking a correction comment as "resolved" does not update the index properly
**Describe the bug**
When a correction comment is marked as "resolved", the task and/or process index is not updated with the new correction comment status. The index still contains the status "2" (process has at least one open correction comment).

**To Reproduce**
1. Create a new correction comment
2. The task list and process list show the red "C"/"K".
3. Mark the correction comment as resolved.
4. The task list and process list still show the red "C"/"K" and not the expected grey "C"/"K".
The process widget does however show the correct grey "C"/"K". (The info is here correctly fetched from database and not from index, like on the task list and process list.

**Release**
3.6.0-SNAPSHOT

**Desktop (please complete the following information):**
 - OS: macOS 13.3
 - Browser: Safari 16.4

### PR DESCRIPTION
**Pull request by solth**
This pull request slightly adjusts the `WorkflowControllerService.solveProblem` function so that a comment's `corrected` flag with value `TRUE` is saved to the database _before_ `closeTaskByUser` is called. That method loads the comment from the database and requires the updated `corrected` state to work properly. 

The updated `corrected` state is then saved to the index field `correctionCommentStatus` which in turn is used to determine whether the grey or red exclamation mark icon should be displayed in the process and task lists. Thereby fixes #5676

### CODE REVIEW

File: Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java [hunk 1]
```diff
@@ -399,12 +406,8 @@ public void solveProblem(Comment comment, TaskEditType taskEditType)
...
         }
         comment.setCurrentTask(ServiceManager.getTaskService().getById(comment.getCurrentTask().getId()));
-        comment.setCorrected(Boolean.TRUE);
-        comment.setCorrectionDate(new Date());
-        try {
-            ServiceManager.getCommentService().saveToDatabase(comment);
-        } catch (DAOException e) {
-            Helper.setErrorMessage("errorSaving", new Object[] {"comment"}, logger, e);
+        if (Objects.nonNull(comment.getProcess())) {
+            comment.setProcess(ServiceManager.getProcessService().getById(comment.getProcess().getId()));
```
Comment (BartChris) [inline Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java:410]: We are setting the currentTask and the process again but do not save the comment object. If calling those setters is necessary should we not persist the comment object again?

**Comment by BartChris** [comment]
Functionality-wise everything works now, i just have a comment.

File: Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java (hunk 1 above)
Comment (solth) [reply Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java:410]: Yes, you are right, this is quite confusing. The reason why we re-add the process (and task!) to the comment without saving it again is that we are making use of a side effect here. This `Comment` object is used again in the calling method afterwards, but with an updated `currentTask` and `process` property. It's not a _different_ process or task that is added here, but rather _updated_ objects, so re-setting these properties in the comment acts as a "refresh" of the object. Since the database entry of the comment only contains the _ID_ of the `process` and the `currentTask`, there is no need to save it again, because the IDs didn't change (e.g. its the same process and currentTask as before, like I mentioned above).

This is indeed implemented in a sub-optimal way and should be refactored more fundamentally when we find the time to do so but right now I do not have the resources for that, unfortunately. I think the bug should be fixed anyway, even if its just an incremental improvement over the status quo and not yet the optimal solution. I can add a comment or `TODO` as a reminder to the code that this code should be refactored and improved, if you like.

**Review by BartChris — APPROVED** [review]

File: Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java (hunk 1 above)
Comment (BartChris) [reply Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java:410]: @solth I see, thanks a lot for the explanation. In think you can go ahead and merge. Adding a TODO would be helpful.
