### PR TITLE
Fall back on installed Chrome version if ChromeDriver version does not match installed Chrome binary

### LINKED ISSUE #6870: Failing builds because current chrome version cannot be fetched for tests
**Describe the bug**
Currently, Selenium tests - and thus automatic builds on GitHub - are failing because the Chrome binaries used in the tests cannot be downloaded. 

**To Reproduce**
1. Check build logs from any recent commit

**Expected behavior**
Current chrome binaries should be automatically downloaded to re-enable Selenium tests and automatic builds.

### PR DESCRIPTION
**Pull request by solth**
Currently, Selenium tests and thus automatic builds on GitHub fail because the latest stable release of Chrome stated on https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json is not yet available on current operating systems. This leads to a mismatch between the versions of the downloaded ChromeDriver (currently 145), which depends on the JSON endpoint mentioned above, and the Chrome binary installed on the system (at the time of writing still 144 on all OS I checked). Therefor the sesssion for the Selenium tests cannot be created, resulting in a `SessionNotCreatedException`, aborted tests and failing builds.

This pull request adds a fallback solution that determines the version of the Chrome binary actually installed locally on the system where the tests are run, whenever such a `SessionNotCreatedException` occurs, and downloading the appropriate ChromeDriver that matches the installed Chrome binary.

Resolves #6870

### CODE REVIEW

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java [hunk 1]
```diff
@@ -87,21 +91,60 @@ private static void provideChromeDriver() throws IOException {
...
+            webDriver = new ChromeDriver(service, options);
+        } catch (SessionNotCreatedException e) {
+            logger.error("SessionNotCreatedException encountered: Chrome driver could not be started");
+            String exceptionMessage = e.getMessage();
+            if (Objects.nonNull(exceptionMessage) && exceptionMessage.contains("Current browser version is")) {
+                Pattern pattern = Pattern.compile(".*?(\\d+\\.\\d+\\.\\d+\\.\\d+).*");
+                Matcher matcher = pattern.matcher(exceptionMessage);
+                if (matcher.find()) {
+                    String version = matcher.group(1);
+                    logger.error("Trying to download Chrome driver for installed Chrome version: {}", version);
```
Comment (henning-gerhardt) [inline Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: I suggest to lower the log level from `error` to `info`.

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java [hunk 2]
```diff
@@ -87,21 +91,60 @@ private static void provideChromeDriver() throws IOException {
...
         }
 
-        ChromeDriverService service = new ChromeDriverService.Builder()
+        ChromeDriverService service = getChromeDriverService(driverFile);
+        ChromeOptions options = getChromeOptions();
+
+        try {
+            webDriver = new ChromeDriver(service, options);
+        } catch (SessionNotCreatedException e) {
+            logger.error("SessionNotCreatedException encountered: Chrome driver could not be started");
```
Comment (henning-gerhardt) [inline Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: Maybe extend the log message about what is happening next so you can interpret the maybe next log messages better and the are belong together. 

F.e. "SessionNotCreatedException encountered: Chrome driver could not be started - try to download Chrome Driver for current installed Chrome version."

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java [hunk 3]
```diff
@@ -87,21 +91,60 @@ private static void provideChromeDriver() throws IOException {
...
+                    service = getChromeDriverService(driverFile);
+                    options = getChromeOptions();
+                    try {
+                        webDriver = new ChromeDriver(service, options);
+                    } catch (SessionNotCreatedException sessionNotCreatedException) {
+                        escalateSessionNotCreatedException("SessionNotCreatedException encountered: Chrome driver could not be started: "
+                                + sessionNotCreatedException.getMessage());
+                    }
+                } else {
+                    escalateSessionNotCreatedException("ERROR: unable to extract Chrome version from exception message!");
```
Comment (henning-gerhardt) [inline Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: Double "ERROR" output? The log message is created on `error` level so the output must not have an `ERROR` prefix.

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java (hunk 1 above)
Comment (solth) [reply Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: I know what you mean, but frankly I disagree. I think all messages in this catch block that begins in line 102 deal with an unexpected situation that as a whole counts as an error. Therefore all messages logged in this catch block should be grouped and logged together, on the same "error" level. (otherwise you may get incomplete information in your log, as you pointed out yourself in the comment below)

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java (hunk 3 above)
Comment (solth) [reply Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: Removed double "ERROR" output

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java [hunk 4]
```diff
@@ -87,21 +91,60 @@ private static void provideChromeDriver() throws IOException {
...
+                }
+            } else {
+                escalateSessionNotCreatedException("ERROR: exception message does not contain information about current Chrome version!");
```
[the remark this answers is not in the document]
Comment (solth) [reply Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: Remove double "ERROR" output

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/helper/WebDriverProvider.java [hunk 5]
```diff
@@ -118,24 +119,31 @@ public static void provideGeckoDriver(String geckoDriverVersion, String download
...
+        }
         String chromeDriverUrl = CHROME_FOR_TESTING_URL + chromeDriverVersion + '/';
         String driverFilename = CHROME_DRIVER;
         File chromeDriverFile;
         if (SystemUtils.IS_OS_WINDOWS) {
             driverFilename = driverFilename + EXE;
             File chromeDriverZipFile = new File(downloadFolder + CHROME_DRIVER_WIN_SUBDIR + File.separator + ZIP_FILE);
-            FileUtils.copyURLToFile(new URL(chromeDriverUrl + CHROME_DRIVER_WIN_PREFIX + '/'
-                    + CHROME_DRIVER_WIN_SUBDIR + ZIP), chromeDriverZipFile);
+            URL chromeUrl = new URL(chromeDriverUrl + CHROME_DRIVER_WIN_PREFIX + '/' + CHROME_DRIVER_WIN_SUBDIR + ZIP);
```
[the remark this answers is not in the document]
Comment (solth) [reply Kitodo/src/test/java/org/kitodo/selenium/testframework/helper/WebDriverProvider.java]: I replaced the deprecated URL constructors in this file as a test. If the solution is ok, I can later perform the same replacements in the other files in the repository (already started that in a different branch, but went for a slightly worse replacement there, so I have to work on it a little more)

File: Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java (hunk 2 above)
Comment (henning-gerhardt) [reply Kitodo/src/test/java/org/kitodo/selenium/testframework/Browser.java]: I'm just suggestion to add an additional information about what it happened next but it could stay as is.

**Review by henning-gerhardt — APPROVED** [review]

**Review by henning-gerhardt — APPROVED** [review]

**Comment by henning-gerhardt** [comment]
Should this changes back ported to `3.8.x` and `3.9.x` branches as they affected from this issue too?
