### PR TITLE
Check whether process is used in ImportConfiguration before deletion

### LINKED ISSUE #6368: Error when trying to delete `templateProcess` used in `ImportConfiguration`
**Describe the bug**
When a process is configured as `templateProcess` (see first screenshot) and additionally this "templateProcess" is used as "Default template process" in an `ImportConfiguration` of type "Process template" (see second screenshot), deleting the process via the bin symbol in the process list results in a generic error messge and leads to a corrupted index, where the process has been removed from the database but not yet from the index.

**To Reproduce**
1. Configure a process as "Template process" (see first screenshot)
2. Create an import configuration of type "Template process" and configure the process of the first step as "Default template process" (second screenshot)
3. Delete process from process list (third screenshot)
4. See error (fourth screenshot)

**Expected behavior**
Deleting a template process used as "Default template process" should either not be possible (display a corresponding error message to the user _before_ it is deleted from the database, that informs him that this process cannot be removed because it is used in an ImportConfiguration) or should update or remove the corresponding ImportConfiguration automatically.

**Screenshots**
Screenshot 1: Configure process as "template process"
Bildschirmfoto 2025-01-16 um 10 42 32

Screenshot 2: Use said process as "Default template process" in corresponding "Import Configuration"
Bildschirmfoto 2025-01-16 um 10 50 14

Screenshot 3: Delete process via list action
Bildschirmfoto 2025-01-16 um 10 51 33

Screenshot 4: See generic error message
Bildschirmfoto 2025-01-16 um 10 51 47

**Release**
3.8, current main branch

### PR DESCRIPTION
**Pull request by solth**
Fixes #6368

### CODE REVIEW

**Review by BartChris — APPROVED** [review]
Looks good and works for me!

File: Kitodo/src/main/java/org/kitodo/production/forms/process/ProcessListBaseView.java [hunk 1]
```diff
@@ -548,19 +553,28 @@ public void uploadFromHome(Process process) {
...
-        }
-        stopwatch.stop();
+            else {
+                this.deleteProcessDialog = new DeleteProcessDialog();
+                this.deleteProcessDialog.setProcess(process);
+                PrimeFaces.current().executeScript("PF('deleteChildrenDialog').show();");
+            }
+        } catch (DAOException e) {
+            Helper.setErrorMessage(ERROR_LOADING_MANY, new Object[]{ObjectType.IMPORT_CONFIGURATION.getTranslationSingular()}, logger, e);
+        } stopwatch.stop();
```
Comment (BartChris) [inline Kitodo/src/main/java/org/kitodo/production/forms/process/ProcessListBaseView.java]: stopwatch should go into the next line.
